#!/usr/bin/env python3

from heatmap import genHeatMap
import os.path
import sys
import json
import tracemalloc

usage = "Usage: gen_heatmap path/to/config.json"

# Load config
configPath = sys.argv[1]
if not os.path.isfile(configPath):
  raise usage

f = open(configPath,)
config = json.load(f)

# Check for default and multi-run, otherwise assume single run
default = config['default'] if 'default' in config else {}
runs = config['runs'] if 'runs' in config else [config]

tracemalloc.start()

for run in runs:
  genHeatMap(**{**default, **run})

print('Peak memory usage: {0} MB'.format(tracemalloc.get_traced_memory()[1]/1000000))
tracemalloc.stop()