name: "Test Docs"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -r requirements_dev.txt
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
      env:
        PYTHONPATH: '/work/lib'