name: "Test Docs"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt  
        python -m pip install -r requirements_dev.txt
    - uses: ammaraskar/sphinx-action@master
      env:
        PYTHONPATH: /home/runner/work/python-sap-map/python-sap-map/lib:/usr/local/lib/python3.8/site-packages
      with:
        docs-folder: "docs/"
